### ISSUE TITLE
Does not works properly with custom navigation bar height

### ISSUE THREAD

**Issue by yasirmturk** [telly/TLYShyNavBar#54] opened 2015-02-25 07:44 UTC
wierd behaviour seen when a custom height `UINavigationBar` is used

**Comment by Mazyod** [comment] 2015-02-25 14:16
I think this is a duplicate of https://github.com/telly/TLYShyNavBar/issues/18. Let me know if you feel otherwise.

**Comment by yasirmturk** [comment] 2015-02-25 18:23
that is about custom `UIStatusBar` height ..but my issue is related to `UINavigationBar` height

**Comment by Mazyod** [comment] 2015-02-28 12:46
@yasirmturk Can you please explain more about how the `UINavigationBar` height is changing?

**Comment by yasirmturk** [comment] 2015-02-28 18:26
@Mazyod for example my app is using a navigation bar of fixed custom height 64px instead of native 44px

**Comment by Mazyod** [comment] 2015-03-01 11:13
@yasirmturk hmm.. I think this is a hack, right? UIKit doesn't provide height changing APIs for `UINavBar`. I will reopen it, anyway, but the solving the status bar comes first, and hopefully it will be easy to fix this as well after that.

**Comment by yasirmturk** [comment] 2015-03-01 16:18
@Mazyod yes it does via over-riding the method
`- (CGSize)sizeThatFits:(CGSize)size`
and you can easily get the actual height via
`frame.size.height`

**Comment by Mazyod** [comment] 2015-10-10 22:24
I am happy to say this should now be possible! The library no longer relies on the topLayoutGuide for layout, but instead uses the navigation bar frame.

Thanks for reporting this @yasirmturk !

**Closed by Mazyod** 2015-10-10 22:24 UTC
