### ISSUE TITLE
Spinner effect doesn't seem to work as well in 1.0.0

### ISSUE THREAD

**Issue by winzig** [telly/TLYShyNavBar#109] opened 2015-12-24 22:42 UTC
In prior versions, the spinner behaved as I would expect, hovering/spinning above the view after pulling down. As shown in this video:

https://www.youtube.com/watch?v=dLjkTVCAnio&feature=youtu.be

In version 1.0.0, the content area seems to snap up too quickly, while the spinner is still operating. As seen here: 

https://www.youtube.com/watch?v=I3tNJubZHeo&feature=youtu.be

Apologies that my refresh action is returning so quickly, but this was the only view I could safely post a video of, and it refreshes very quickly, but I think you can see the difference between the older version and the new one.

**Comment by Mazyod** [comment] 2015-12-29 20:14
thanks for reporting this, however, it is in fact a duplicate of #99. You can follow that issue for updates. There is a workaround posted there, but a better and more general solution is yet to be introduced.

**Closed by Mazyod** 2015-12-29 20:14 UTC
