### ISSUE TITLE
Black navigation bar with UITableView

### ISSUE THREAD

**Issue by shahankit** [telly/TLYShyNavBar#64] opened 2015-04-03 08:14 UTC
I have a tableview I assigned `self.tableView` to `self.shyNavBarManager.scrollView`. But on scroll up it shows black background while moving up. Seems possibly because of header constraints setup on tableview. Also when I select a row in tableview it moves to new viewcontroller, the navigation bar shows in status bar. But somehow on pulling down the notification bar fixes the navigation bar. Also I have pull to refresh in tableview which leads to problem.

**Comment by yuchaozh** [comment] 2015-09-09 20:17
Hi, I am having the same problem right now. Have you solved this issue?

**Comment by shahankit** [comment] 2015-09-10 09:56
No @yuchaozh I didn't. I finally wrote my own solution for hiding  and showing navigation with scroll view. Can share the code if you want.

**Comment by Mazyod** [comment] 2015-10-10 22:14
Guess it's duplicate of #63

**Closed by Mazyod** 2015-10-10 22:14 UTC
