### ISSUE TITLE
How to not autoshow the navigationbar when back?

### ISSUE THREAD

**Issue by nypisces** [telly/TLYShyNavBar#46] opened 2015-01-28 17:46 UTC
In controller A, I scroll to top, the navigationbar work fine and  hide, and click a push segue go to the next controller B.
When I back to pre controll A, navigationbar always auto show again.
How to dismiss it?

**Comment by Mazyod** [comment] 2015-01-29 10:52
This is a duplicate of #8, it still hasn't been resolved.

**Closed** 2015-01-29 14:44 UTC
