### ISSUE TITLE
Views in Navbar disappear when rotating while shrunk

### ISSUE THREAD

**Issue by kylebshr** [telly/TLYShyNavBar#51] opened 2015-02-20 00:53 UTC
First time posting an issue; hope I'm not breaking an "rules"

Anyways, I'm using TLYShyNavBar with a TableView and it works great for the most part. However, the Title object in my NavBar disappears when the NavBar is "shy," as seen in this video: http://youtu.be/Eb2B4J040ak

My NavBar is Opaque, and I fixed that bug with `self.extendedLayoutIncludesOpaqueBars = true` — not sure if that's affecting it. 
 
Let me know if any other info is needed. Thanks!

**Comment by kylebshr** [comment] 2015-02-21 16:33
After some testing, this only happens when translucency is off.

**Comment by Mazyod** [comment] 2015-03-13 10:22
Then probably it's a duplicate of #7 , thanks for the report!

**Closed by Mazyod** 2015-03-13 10:22 UTC
